// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGW9V15veOahbXs8Q5egbwbZ1G9LAVGY',
    appId: '1:775289023297:web:2ccd500e033172b989cfc0',
    messagingSenderId: '775289023297',
    projectId: 'flutterapp-dde40',
    authDomain: 'flutterapp-dde40.firebaseapp.com',
    storageBucket: 'flutterapp-dde40.firebasestorage.app',
    measurementId: 'G-B4DW92RKDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRosw39jnp_iw5O0U1SguUCtaOZtCTRo',
    appId: '1:775289023297:android:6a6f78e6fc6b728489cfc0',
    messagingSenderId: '775289023297',
    projectId: 'flutterapp-dde40',
    storageBucket: 'flutterapp-dde40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyzAwcQ_blb7bWmK-iNOG6pWOJGJ7bj0',
    appId: '1:775289023297:ios:cda80656ad1f077789cfc0',
    messagingSenderId: '775289023297',
    projectId: 'flutterapp-dde40',
    storageBucket: 'flutterapp-dde40.firebasestorage.app',
    iosBundleId: 'com.example.vnclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQyzAwcQ_blb7bWmK-iNOG6pWOJGJ7bj0',
    appId: '1:775289023297:ios:cda80656ad1f077789cfc0',
    messagingSenderId: '775289023297',
    projectId: 'flutterapp-dde40',
    storageBucket: 'flutterapp-dde40.firebasestorage.app',
    iosBundleId: 'com.example.vnclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPGW9V15veOahbXs8Q5egbwbZ1G9LAVGY',
    appId: '1:775289023297:web:b1d47d9b8cad52a689cfc0',
    messagingSenderId: '775289023297',
    projectId: 'flutterapp-dde40',
    authDomain: 'flutterapp-dde40.firebaseapp.com',
    storageBucket: 'flutterapp-dde40.firebasestorage.app',
    measurementId: 'G-03SR00BJRD',
  );
}
